### ISSUE TITLE
Should the & operator perform a cartesian product?

### ISSUE THREAD

**Issue by pygy** [j2css/j2c#18]
With SASS and LESS (but not Stylus), 

```SCSS
p, a {
    & + & {
        color: red;
    }
}
```

Expands to 

```CSS
p + p, a + p, p + a, a + a {
  color: red;
}
```

It may be nice to emulate that behavior, for consistency.
