### ISSUE TITLE
hook > selector for old IE

### ISSUE THREAD

**Issue by futurist** [j2css/j2c#19]
If can hook > selector to let css support old IE that don't support child selector.
````js
'ul>ul': {
  color: 'red'
}
````
If j2c can hook into the selector to js parser(maybe generate some temp long classname?) to let j2c support old IE? maybe generate below css:
````css
ul ul.temp_secondlevel_ul  {
  color: red;
}
````
